// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV_EwW9GDBN0Fad1v6ccyhdPjv4hF7QFY',
    appId: '1:856840318451:web:f6d45ed3d0bd31c8d63686',
    messagingSenderId: '856840318451',
    projectId: 'neighborhoodfinds-64',
    authDomain: 'neighborhoodfinds-64.firebaseapp.com',
    storageBucket: 'neighborhoodfinds-64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQx5nq0jYhmsMFcTE5CIEgmnirS3sYO5k',
    appId: '1:856840318451:android:8a907d824527ce78d63686',
    messagingSenderId: '856840318451',
    projectId: 'neighborhoodfinds-64',
    storageBucket: 'neighborhoodfinds-64.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV_EwW9GDBN0Fad1v6ccyhdPjv4hF7QFY',
    appId: '1:856840318451:web:3b5328a498729c1cd63686',
    messagingSenderId: '856840318451',
    projectId: 'neighborhoodfinds-64',
    authDomain: 'neighborhoodfinds-64.firebaseapp.com',
    storageBucket: 'neighborhoodfinds-64.firebasestorage.app',
  );
}
